# Generated by Django 3.0.6 on 2020-11-28 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255, unique=True, verbose_name='Name')),
                ('introduction', models.TextField(help_text='Introduction', verbose_name='Introduction')),
                ('rating', models.IntegerField(help_text='Rating', verbose_name='Rating')),
                ('location', models.TextField(help_text='Location', verbose_name='Location')),
                ('longitude', models.DecimalField(decimal_places=2, help_text='Longitude', max_digits=6, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=2, help_text='Latitude', max_digits=6, verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Stations',
                'verbose_name_plural': 'Stations',
                'ordering': ('rating',),
            },
        ),
    ]
