# Generated by Django 3.0.6 on 2020-11-29 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=255, unique=True, verbose_name='Name')),
                ('introduction', models.TextField(help_text='Introduction', verbose_name='Introduction')),
                ('rating', models.IntegerField(help_text='Rating', verbose_name='Rating')),
                ('num_of_comments', models.IntegerField(help_text='Number of Comments', verbose_name='Number of Comments')),
                ('features', models.TextField(help_text='Features', verbose_name='Features')),
                ('category', models.TextField(help_text='Category', verbose_name='Category')),
                ('thumbnail_url', models.TextField(help_text='Thumbnail URL', verbose_name='Thumbnail URL')),
                ('image_url', models.TextField(help_text='Image URL', verbose_name='Image URL')),
                ('started_at', models.DateTimeField(help_text='Started At', verbose_name='Started At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(help_text='Owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('station', models.ForeignKey(help_text='Station', on_delete=django.db.models.deletion.CASCADE, to='stations.Station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Shops',
                'verbose_name_plural': 'Shops',
                'ordering': ('rating',),
            },
        ),
    ]
